server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf67y80n56vo4335vo.mysql.rds.aliyuncs.com:3306/test
    username: root
    password: Selegant#1285